"""data_gen_templates package.

Python templates that turn the hand-authored source data in `data_gen/`
into the generated `data/` package. `data_gen.py` (repository root) is the
entry point that drives this module -- see docs/architecture.md, "## Layout".

Bootstrap step (task C1): a single generated module, `data/__init__.py`,
built from `data_gen/game_version.toml`. Task C2 adds `data/species.py` and
`data/moves.py`, built from `data_gen/species.toml` and `data_gen/moves.toml`
respectively (see `data_gen_templates/species.py`, `data_gen_templates/moves.py`).
Task C3 adds `data/items.py`, built from `data_gen/items.toml` (see
`data_gen_templates/items.py`). Task C4 adds `data/regions.py` and
`data/locations.py` (Johto only; Kanto is a future task), built from
`data_gen/regions.toml` and `data_gen/locations.toml` (see
`data_gen_templates/regions.py`, `data_gen_templates/locations.py`). Future
steps will add more `data_gen/*.toml` sources plus one `generate_*` function
per generated module here, following the same pattern.
"""

from __future__ import annotations

import sys
import tomllib
from collections.abc import Mapping
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_GEN_DIR = REPO_ROOT / "data_gen"

GENERATED_FILE_HEADER = (
    "# THIS IS AN AUTO-GENERATED FILE. DO NOT MODIFY.\n"
    "# Generated by data_gen.py from data_gen/. See docs/architecture.md.\n"
)


def load_toml(name: str) -> Mapping[str, Any]:
    """Load a `data_gen/<name>.toml` source file."""
    with (DATA_GEN_DIR / f"{name}.toml").open("rb") as f:
        return tomllib.load(f)


def _check_decomp_paths_exist(rom_interface: Mapping[str, Any]) -> None:
    """Best-effort sanity check that `data_gen/rom_interface.toml`'s declared
    decomp paths still resolve (see docs/architecture.md Spike 3: the decomp
    is a reliable but not 100% trustworthy source of truth).

    `ressources/` is a git-ignored, read-only external checkout that may
    legitimately be absent (e.g. before it has been fetched locally), so
    this warns instead of failing -- it must not break `data_gen.py` for
    data that doesn't actually need the decomp to be present.
    """
    paths = rom_interface.get("paths", {})
    decomp_root = REPO_ROOT / paths.get("decomp_root", "")
    for key, rel_path in paths.items():
        if key == "decomp_root":
            continue
        full_path = decomp_root / rel_path
        if not full_path.is_file():
            print(
                f"warning: data_gen/rom_interface.toml: paths.{key} does not resolve "
                f"to an existing file ({full_path}); skipping sanity check.",
                file=sys.stderr,
            )


def generate_init() -> str:
    """Build the contents of `data/__init__.py`."""
    game_version = load_toml("game_version")
    _check_decomp_paths_exist(load_toml("rom_interface"))

    lines = [GENERATED_FILE_HEADER, "\n", "GAME_VERSION = {\n"]
    for key, value in game_version.items():
        lines.append(f"    {key!r}: {value!r},\n")
    lines.append("}\n")
    return "".join(lines)


# Imported at the bottom of the module: `species`, `moves` and `items` all
# call `load_toml`/reference `GENERATED_FILE_HEADER` from this module at
# import time, so they must be defined above before these submodules are
# imported.
from .items import generate_items  # noqa: E402
from .locations import generate_locations  # noqa: E402
from .moves import generate_moves  # noqa: E402
from .regions import generate_regions  # noqa: E402
from .species import generate_species  # noqa: E402

__all__ = [
    "generate_init",
    "generate_items",
    "generate_locations",
    "generate_moves",
    "generate_regions",
    "generate_species",
]
